FROM ubuntu:20.04
RUN apt-get update && apt-get install -y apt-utils git python3.8 python3.8-dev tmux vim
RUN apt-get install -y python3-pip
RUN pip install pydantic==1.7.4
RUN pip install protobuf==3.20.*
RUN pip install fedml
RUN pip install scapy
