apiVersion: v1
kind: Pod
metadata:
  name: alice-test
spec:
  containers:
  - name: alice-test
    image: praqma/network-multitool
    command:
      - sleep
      - infinity
    imagePullPolicy: IfNotPresent
